# Generated by Django 5.2.6 on 2025-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('street_number', models.TextField()),
                ('street_name', models.TextField()),
                ('apt_number', models.TextField()),
                ('zip_code', models.TextField()),
                ('birth', models.TextField()),
                ('date_time', models.DateField()),
                ('date_reg', models.DateField()),
                ('party_aff', models.CharField(max_length=2)),
                ('precinct', models.CharField(max_length=10)),
                ('v20state', models.TextField()),
                ('v21town', models.TextField()),
                ('v21primary', models.TextField()),
                ('v22general', models.TextField()),
                ('v23town', models.TextField()),
                ('voter_score', models.CharField(max_length=5)),
            ],
        ),
    ]
