# Generated by Django 5.2.6 on 2025-10-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.CharField(max_length=100),
        ),
    ]
