# Generated by Django 5.2.6 on 2025-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.TextField(blank=True),
        ),
    ]
